version: '3'

services:
### NGINX Server + PHP-FPM #########################################
  nginx-php-fpm:
    build:
      context: ./../
      dockerfile: ./.docker-laravel/nginx-php-fpm/Dockerfile
      args:
        - INSTALL_XDEBUG=false
    volumes: []
    ports:
      - "80:80"
      - "443:443"
